version: '3.8'

services:
  server_small:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "50051:50051"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 100M
        reservations:
          cpus: '0.1'
          memory: 100M

  server_medium:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "50052:50051"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 1G

  server_large:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "50053:50051"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 8G
        reservations:
          cpus: '0.5'
          memory: 8G
